stages:
  - build
  - release
  - deploy

include:
  - project: 'infrastructure/ci-scripts'
    file: 'build-docker-image.yml'
  - project: 'infrastructure/ci-scripts'
    file: 'release-docker-image.yml'
  - project: 'infrastructure/ci-scripts'
    file: 'deploy-kustomize.yml'

build:
  extends: .build_image
  only:
    - master

release:
  extends: .release_image
  only:
    - master

deploy:
  extends: .deploy_kustomize
  variables:
    KUSTOMIZE_OVERLAY: 'k8s'
  only:
    - master
  environment:
    name: prod
